import type { ModelDefinition } from "../../domain/model/types";

export const deepseekV4Models: ModelDefinition[] = [
  {
    family: "deepseek-v4",
    id: "deepseek-v4-flash",
    displayName: "DeepSeek-V4-Flash",
    contextLimit: 131072,
    decoderLayers: 43,
    hiddenSize: 4096,
    attentionHeads: 64,
    kvHeads: 1,
    headDim: 512,
    qLoraRank: 1024,
    oLoraRank: 1024,
    oGroups: 8,
    indexHeads: 64,
    indexHeadDim: 128,
    indexTopk: 512,
    slidingWindow: 128,
    csaCompressRate: 4,
    hcaCompressRate: 128,
    moeExperts: 128,
    activeExperts: 6,
    moeIntermediateSize: 2048,
    csaLayerCount: 21,
    hcaLayerCount: 20,
    slidingLayerCount: 2,
    estimatedWeightsGb: 145.82
  },
  {
    family: "deepseek-v4",
    id: "deepseek-v4-pro",
    displayName: "DeepSeek-V4-Pro",
    contextLimit: 131072,
    decoderLayers: 61,
    hiddenSize: 7168,
    attentionHeads: 128,
    kvHeads: 1,
    headDim: 512,
    qLoraRank: 1536,
    oLoraRank: 1024,
    oGroups: 16,
    indexHeads: 64,
    indexHeadDim: 128,
    indexTopk: 1024,
    slidingWindow: 128,
    csaCompressRate: 4,
    hcaCompressRate: 128,
    moeExperts: 384,
    activeExperts: 6,
    moeIntermediateSize: 3072,
    csaLayerCount: 30,
    hcaLayerCount: 31,
    slidingLayerCount: 0,
    estimatedWeightsGb: 799.31
  }
];
